output_root: "outputs"
output_version: "baseline"
backup_name: "weights"
log_name: "logs"

labels: ["aeroplane","bicycle","bird","boat","bottle","bus","car","cat","chair","cow","diningtable","dog","horse","motorbike","person","pottedplant","sheep","sofa","train","tvmonitor"]
anchors: "10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326"
anchors_mask:
 - "6,9"
 - "3,6"
 - "0,3"
data_root_dir: "/home/zhou/data/voc"
sets:
 - "VOC2007"
 - "VOC2012"

MAX_BOXES: 90

train:
    dataset: "train"
    stdout: False
    gpus: "0"
    nworkers: 16
    pin_mem: True

    momentum: 0.9
    decay: 0.0005

    clear: False

    warmup_lr: 0.00005
    lr_steps: [400,700,900,1000, 40000,45000]
    lr_rates: [0.0001,0.0002,0.0005,0.001, 0.0001,0.00001]
    max_batches: 50200
    resize_interval: 10

    backup_interval: 200
    backup_steps: [1000]
    backup_rates: [10000]

    input_shape: [608, 608]
    batch_size: 64
    mini_batch_size: 4
    max_boxes: 90
    weights: "data/darknet53.conv.74"

test:
    dataset: "test"
    stdout: True
    gpus: "0"
    nworkers: 8
    pin_mem: True

    input_shape: [416, 416]
    batch_size: 8
    weights: "data/yolov3_50200.dw"

    conf_thresh: 0.005
    nms_thresh: 0.45
    batch_size: 64
    mini_batch_size: 8

    results: "results"

speed:
    gpus: "7"
    batch_size: 1
    max_iters: 200
    input_shape: [544, 544]

detect:
    yolodevice: "cpu"
    conf_thresh: 0.5
    ignore_thresh: 0.4




